=== iamcrowd/metamodel-api/src/main/resources/schemas/ormSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gilia.metamodel.orm",
  "title": "ORM JSON",
  "description": "This JSON represents the information represented by a model described in ORM modeling language",
  "type": "object",
  "properties": {
    "namespaces": {
      "description": "",
      "type": "object",
      "properties": {
        "ontologyIRI": {
          "description": "",
          "type": "object",
          "properties": {
            "prefix": {
              "description": "",
              "type": "string"
            },
            "value": {
              "description": "",
              "type": "string"
            }
          },
          "required": [
            "prefix",
            "value"
          ]
        }
      }
    },
    "entities": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "attributes": {
      "description": "",
      "type": "array"
    },
    "relationships": {
      "description": "",
      "type": "array"
    },
    "inheritances": {
      "description": "",
      "type": "array"
    },
    "connectors": {
      "description": "",
      "type": "array"
    }
  },
  "required": [
    "entities",
    "attributes",
    "relationships",
    "inheritances",
    "connectors"
  ]
}

=== iamcrowd/metamodel-api/src/main/resources/jsonExamples/ormExample.json
{
  "entities": [
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Entity",
      "ref": "",
      "id": 60,
      "type": "entity",
      "position": {
        "x": 250,
        "y": 195
      }
    },
    {
      "name": "http://crowd.fi.uncoma.edu.ar#Entity",
      "ref": "",
      "id": 74,
      "type": "entity",
      "position": {
        "x": 585,
        "y": 200
      }
    }
  ],
  "relationships": [
    {
      "name": "http://crowd.fi.uncoma.edu.ar#role_name",
      "inverseReading": false,
      "entities": [
        "http://crowd.fi.uncoma.edu.ar#undefined",
        "http://crowd.fi.uncoma.edu.ar#Entity",
        "http://crowd.fi.uncoma.edu.ar#undefined",
        "http://crowd.fi.uncoma.edu.ar#Entity"
      ],
      "uniquenessConstraints": [
        "0..1",
        "0..1"
      ],
      "mandatory": [],
      "type": "binaryFactType",
      "position": {
        "x": 430,
        "y": 210
      }
    }
  ],
  "attributes": [],
  "inheritances": [],
  "connectors": []
}
